# codetonic-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codetonic-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codetonic
  template:
    metadata:
      labels:
        app: codetonic
    spec:
      containers:
      - name: codetonic
        image: yourdockerhubuser/codetonic:v1
        ports:
        - containerPort: 80